name: real_gripper_6dof_image

image_shape: [3, 240, 320]
dataset_path: data/demo_pusht_real_emil_30_delay

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera_0:
      shape: ${task.image_shape}
      type: rgb
    camera_1:
      shape: ${task.image_shape}
      type: rgb
    # camera_2:
    #   shape: ${task.image_shape}
    #   type: rgb
    #camera_3:
    #  shape: ${task.image_shape}
    #  type: rgb
    # camera_4:
    #   shape: ${task.image_shape}
    #   type: rgb
    robot_eef_pose: 
      shape: [6]
      type: low_dim
    ft_ee_wrench:
      shape: [6]
      type: low_dim
  action: 
    shape: [7] #6dof float, gripper bool


env_runner:
  _target_: diffusion_policy.env_runner.real_image_runner.RealImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_tool_image_dataset.RealToolImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False

